services:
  - type: web
    name: sparkle247
    runtime: node
    plan: starter
    region: frankfurt
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_SUPPORT_PHONE
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: EMAIL_FROM
        value: 247Sparkle <no-reply@247sparkle.com>
      - key: SEED_ADMIN_EMAIL
        value: admin@247sparkle.com
      - key: SEED_ADMIN_PASSWORD
        sync: false
      - key: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
        sync: false
